name: 배포

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub 저장소에서 파일 가져오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Gradle 권한 부여
        run: chmod +x gradlew

      - name: .env 파일 생성
        run: |
          echo "GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" > .env
          echo "GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env

      - name: .env 파일 확인
        run: cat .env

      - name: 테스트 및 빌드
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./release.jar

      - name: SCP로 EC2에 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 2222
          source: "./release.jar"
          target: "/home/ubuntu/howread-server/tobe"

      - name: SCP로 .env 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 2222
          source: "./.env"
          target: "/home/ubuntu/howread-server/current/.env"

      - name: .env 파일이 EC2에 전송되었는지 확인
        run: ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -p 2222 ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'cat /home/ubuntu/howread-server/current/.env'

      - name: SSH로 EC2에 접속하여 애플리케이션 시작
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 2222
          script: |
            rm -rf /home/ubuntu/howread-server/current
            mkdir /home/ubuntu/howread-server/current
            mv /home/ubuntu/howread-server/tobe/release.jar /home/ubuntu/howread-server/current
            cd /home/ubuntu/howread-server/current
            export $(grep -v '^#' .env | xargs) # .env 파일의 내용을 환경 변수로 설정
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar release.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/howread-server/tobe